[package]
name = "gridiron"
version = "0.1.0"
authors = ["Jonathan Zrake <jonathan.zrake@gmail.com>"]
edition = "2018"

[dependencies]
rayon = "1.5"
crossbeam-channel = "0.5"
serde = { version = "1.0", features = ["derive"] }
ciborium = "0.1"
